# 02-14 nnU-Net PHE with ICH teacher prior

Notebook nay dung ICH teacher da train o `02_13` de predict ICH tren PHE-SICH, sau do train PHE nnU-Net voi 2 channel:

```text
channel 0 = CT
channel 1 = ICH teacher prior mask
label     = manual PHE mask
```

Quan trong: notebook nay khong train lai ICH teacher. ICH teacher chi duoc load checkpoint va chay inference de tao prior.

In [1]:
from pathlib import Path
import os
import sys
import json
import shutil
import time
import gc

import numpy as np
import pandas as pd

PROJECT_ROOT = Path.cwd().resolve()
NNUNET_REPO = PROJECT_ROOT / 'nnUNet-master'

PHE_ROOT = PROJECT_ROOT / 'PHE-SICH-CT-IDS' / 'SubdatasetA_NIFIT' / 'NIFIT'
PHE_IMAGE_DIR = PHE_ROOT / 'set'
PHE_MASK_DIR = PHE_ROOT / 'label'
SPLIT_CSV = PROJECT_ROOT / 'outputs_02_10_pese_guided_3dff_refined_pseudo_iph_phe_25d_segmentation' / 'manifests' / '3dff_iph_phe_patient_split.csv'

ICH_TEACHER_ROOT = PROJECT_ROOT / 'outputs_02_13_nnunet_ich_teacher_external'
ICH_TEACHER_DATASET_NAME = 'Dataset113_ExternalICHTeacher'
ICH_TEACHER_CONFIGURATION = '3d_fullres'
ICH_TEACHER_TRAINER = 'nnUNetTrainer_250epochs'
ICH_TEACHER_PLANS = 'nnUNetPlans'
ICH_TEACHER_FOLD = 0
ICH_TEACHER_CHECKPOINT = 'checkpoint_best.pth'
ICH_TEACHER_MODEL_DIR = (
    ICH_TEACHER_ROOT / 'nnunet_workdir' / 'nnUNet_results' / ICH_TEACHER_DATASET_NAME /
    f'{ICH_TEACHER_TRAINER}__{ICH_TEACHER_PLANS}__{ICH_TEACHER_CONFIGURATION}'
)
ICH_TEACHER_CHECKPOINT_PATH = ICH_TEACHER_MODEL_DIR / f'fold_{ICH_TEACHER_FOLD}' / ICH_TEACHER_CHECKPOINT

OUTPUT_ROOT = PROJECT_ROOT / 'outputs_02_14_nnunet_phe_ich_teacher_prior'
NNUNET_BASE = OUTPUT_ROOT / 'nnunet_workdir'
NNUNET_RAW = NNUNET_BASE / 'nnUNet_raw'
NNUNET_PREPROCESSED = NNUNET_BASE / 'nnUNet_preprocessed'
NNUNET_RESULTS = NNUNET_BASE / 'nnUNet_results'

DATASET_ID = 114
DATASET_NAME = f'Dataset{DATASET_ID:03d}_PHESICH_PHE_ICHTeacherPrior'
DATASET_DIR = NNUNET_RAW / DATASET_NAME

ICH_INPUT_DIR = OUTPUT_ROOT / 'ich_teacher_inputs_phe_sich'
ICH_PRIOR_MASK_DIR = OUTPUT_ROOT / 'ich_teacher_prior_masks'

for p in [OUTPUT_ROOT, NNUNET_RAW, NNUNET_PREPROCESSED, NNUNET_RESULTS, ICH_INPUT_DIR, ICH_PRIOR_MASK_DIR]:
    p.mkdir(parents=True, exist_ok=True)

os.environ['nnUNet_raw'] = str(NNUNET_RAW)
os.environ['nnUNet_preprocessed'] = str(NNUNET_PREPROCESSED)
os.environ['nnUNet_results'] = str(NNUNET_RESULTS)
os.environ['nnUNet_n_proc_DA'] = '0'
os.environ['nnUNet_compile'] = 'False'

if str(NNUNET_REPO) not in sys.path:
    sys.path.insert(0, str(NNUNET_REPO))

assert NNUNET_REPO.exists(), f'Missing nnU-Net repo: {NNUNET_REPO}'
assert PHE_IMAGE_DIR.exists(), f'Missing PHE image dir: {PHE_IMAGE_DIR}'
assert PHE_MASK_DIR.exists(), f'Missing PHE mask dir: {PHE_MASK_DIR}'
assert SPLIT_CSV.exists(), f'Missing split CSV: {SPLIT_CSV}'
assert ICH_TEACHER_CHECKPOINT_PATH.exists(), f'Missing ICH teacher checkpoint: {ICH_TEACHER_CHECKPOINT_PATH}'

print('Project root          :', PROJECT_ROOT)
print('nnU-Net repo          :', NNUNET_REPO)
print('PHE image dir         :', PHE_IMAGE_DIR)
print('PHE mask dir          :', PHE_MASK_DIR)
print('Split CSV            :', SPLIT_CSV)
print('ICH teacher model    :', ICH_TEACHER_MODEL_DIR)
print('ICH teacher ckpt     :', ICH_TEACHER_CHECKPOINT_PATH)
print('Output root          :', OUTPUT_ROOT)
print('Dataset              :', DATASET_NAME)
print('nnUNet_raw           :', os.environ['nnUNet_raw'])
print('nnUNet_preprocessed  :', os.environ['nnUNet_preprocessed'])
print('nnUNet_results       :', os.environ['nnUNet_results'])

Project root          : D:\Thuy_Loi\Nam_3\CT_xuathuyetnao
nnU-Net repo          : D:\Thuy_Loi\Nam_3\CT_xuathuyetnao\nnUNet-master
PHE image dir         : D:\Thuy_Loi\Nam_3\CT_xuathuyetnao\PHE-SICH-CT-IDS\SubdatasetA_NIFIT\NIFIT\set
PHE mask dir          : D:\Thuy_Loi\Nam_3\CT_xuathuyetnao\PHE-SICH-CT-IDS\SubdatasetA_NIFIT\NIFIT\label
Split CSV            : D:\Thuy_Loi\Nam_3\CT_xuathuyetnao\outputs_02_10_pese_guided_3dff_refined_pseudo_iph_phe_25d_segmentation\manifests\3dff_iph_phe_patient_split.csv
ICH teacher model    : D:\Thuy_Loi\Nam_3\CT_xuathuyetnao\outputs_02_13_nnunet_ich_teacher_external\nnunet_workdir\nnUNet_results\Dataset113_ExternalICHTeacher\nnUNetTrainer_250epochs__nnUNetPlans__3d_fullres
ICH teacher ckpt     : D:\Thuy_Loi\Nam_3\CT_xuathuyetnao\outputs_02_13_nnunet_ich_teacher_external\nnunet_workdir\nnUNet_results\Dataset113_ExternalICHTeacher\nnUNetTrainer_250epochs__nnUNetPlans__3d_fullres\fold_0\checkpoint_best.pth
Output root          : D:\Thuy_Loi\Nam_3\CT_xuathuyetnao\outputs_02_14_nnunet_phe_ich_teacher_prior
Dataset              : Dataset114_PHESICH_PHE_ICHTeacherPrior
nnUNet_raw           : D:\Thuy_Loi\Nam_3\CT_xuathuyetnao\outputs_02_14_nnunet_phe_ich_teacher_prior\nnunet_workdir\nnUNet_raw
nnUNet_preprocessed  : D:\Thuy_Loi\Nam_3\CT_xuathuyetnao\outputs_02_14_nnunet_phe_ich_teacher_prior\nnunet_workdir\nnUNet_preprocessed
nnUNet_results       : D:\Thuy_Loi\Nam_3\CT_xuathuyetnao\outputs_02_14_nnunet_phe_ich_teacher_prior\nnunet_workdir\nnUNet_results

## 0. Dependency check

In [2]:
AUTO_INSTALL_MISSING_DEPS = False
INSTALL_NNUNET = False

def ensure_import(import_name, pip_name=None):
    import importlib
    import subprocess
    pip_name = pip_name or import_name
    try:
        return importlib.import_module(import_name)
    except ModuleNotFoundError:
        if not AUTO_INSTALL_MISSING_DEPS:
            raise
        cmd = [sys.executable, '-m', 'pip', 'install', pip_name]
        print('Missing', import_name, '-> running:', ' '.join(cmd))
        subprocess.check_call(cmd)
        return importlib.import_module(import_name)

if INSTALL_NNUNET:
    import subprocess
    cmd = [sys.executable, '-m', 'pip', 'install', '-e', str(NNUNET_REPO)]
    print('Running:', ' '.join(cmd))
    subprocess.check_call(cmd)

ensure_import('SimpleITK')
ensure_import('nnunetv2')

import SimpleITK as sitk
import nnunetv2
print('SimpleITK OK')
print('nnunetv2 import OK:', nnunetv2.__file__)

SimpleITK OK
nnunetv2 import OK: D:\Thuy_Loi\Nam_3\CT_xuathuyetnao\nnUNet-master\nnunetv2\__init__.py

## 1. Inspect split PHE-SICH

Dung lai split tu `02_10`/`02_12`: train 99, val 10, test 11.

In [3]:
split_df = pd.read_csv(SPLIT_CSV, dtype={'scan_id': str, 'patient_id': str})
split_df.columns = [str(c).strip() for c in split_df.columns]

def make_nnunet_case_id(value, img_path=None):
    value = '' if value is None or pd.isna(value) else str(value).strip()
    if not value and img_path is not None:
        name = Path(str(img_path)).name
        value = name.replace('.nii.gz', '').replace('.nii', '')
    if value.lower().startswith('phe_'):
        return value
    if value.isdigit():
        return f'phe_{int(value):04d}'
    safe = ''.join(ch if ch.isalnum() else '_' for ch in value).strip('_')
    return f'phe_{safe}' if not safe.lower().startswith('phe_') else safe

if 'patient_id' in split_df.columns:
    split_df['case_id'] = [make_nnunet_case_id(v, p) for v, p in zip(split_df['patient_id'], split_df['img_path'])]
elif 'scan_id' in split_df.columns:
    split_df['case_id'] = [make_nnunet_case_id(v, p) for v, p in zip(split_df['scan_id'], split_df['img_path'])]
else:
    split_df['case_id'] = [make_nnunet_case_id(None, p) for p in split_df['img_path']]

required_cols = {'case_id', 'split', 'img_path', 'phe_mask_path'}
missing_cols = required_cols - set(split_df.columns)
assert not missing_cols, f'Missing columns in split CSV: {missing_cols}'
assert split_df['case_id'].is_unique, 'case_id must be unique.'

split_df['img_exists'] = split_df['img_path'].map(lambda x: Path(x).exists())
split_df['mask_exists'] = split_df['phe_mask_path'].map(lambda x: Path(x).exists())
assert split_df['img_exists'].all(), 'Some image paths are missing.'
assert split_df['mask_exists'].all(), 'Some PHE mask paths are missing.'

display(split_df.groupby('split').agg(
    cases=('case_id', 'count'),
    slices=('n_slices', 'sum'),
    phe_positive_slices=('phe_positive_slices', 'sum'),
    total_phe_ml=('phe_volume_ml', 'sum'),
))
display(split_df[['case_id', 'split', 'img_path', 'phe_mask_path']].head())
split_df.to_csv(OUTPUT_ROOT / '02_14_phe_sich_split_manifest.csv', index=False)
print('Total cases:', len(split_df))

       cases  slices  phe_positive_slices  total_phe_ml
split
test      11     329                   62     31.534920
train     99    2983                  560    355.115621
val       10     289                   61     34.999343

,case_id,split,img_path,phe_mask_path
0,phe_0001,train,D:\Thuy_Loi\Nam_3\CT_xuathuyetnao\PHE-SICH-CT-...,D:\Thuy_Loi\Nam_3\CT_xuathuyetnao\PHE-SICH-CT-...
1,phe_0002,test,D:\Thuy_Loi\Nam_3\CT_xuathuyetnao\PHE-SICH-CT-...,D:\Thuy_Loi\Nam_3\CT_xuathuyetnao\PHE-SICH-CT-...
2,phe_0004,train,D:\Thuy_Loi\Nam_3\CT_xuathuyetnao\PHE-SICH-CT-...,D:\Thuy_Loi\Nam_3\CT_xuathuyetnao\PHE-SICH-CT-...
3,phe_0005,train,D:\Thuy_Loi\Nam_3\CT_xuathuyetnao\PHE-SICH-CT-...,D:\Thuy_Loi\Nam_3\CT_xuathuyetnao\PHE-SICH-CT-...
4,phe_0006,train,D:\Thuy_Loi\Nam_3\CT_xuathuyetnao\PHE-SICH-CT-...,D:\Thuy_Loi\Nam_3\CT_xuathuyetnao\PHE-SICH-CT-...

Total cases: 120

## 2. Predict ICH prior on PHE-SICH

Cell nay chi load checkpoint ICH teacher tu `02_13` va predict mask ICH cho toan bo case PHE-SICH. Khong train lai ICH.

In [4]:
RUN_ICH_PRIOR_PREDICT = True
OVERWRITE_ICH_INPUTS = True
OVERWRITE_ICH_PRIORS = False
ICH_DISABLE_TTA = False

if OVERWRITE_ICH_INPUTS and ICH_INPUT_DIR.exists():
    shutil.rmtree(ICH_INPUT_DIR)
ICH_INPUT_DIR.mkdir(parents=True, exist_ok=True)
ICH_PRIOR_MASK_DIR.mkdir(parents=True, exist_ok=True)

input_records = []
for row in split_df.itertuples(index=False):
    case_id = str(row.case_id)
    src = Path(row.img_path)
    dst = ICH_INPUT_DIR / f'{case_id}_0000.nii.gz'
    if OVERWRITE_ICH_INPUTS or not dst.exists():
        shutil.copy2(src, dst)
    input_records.append({'case_id': case_id, 'split': row.split, 'ich_teacher_input': str(dst)})

ich_input_df = pd.DataFrame(input_records)
ich_input_df.to_csv(OUTPUT_ROOT / '02_14_ich_teacher_input_manifest.csv', index=False)

expected_prior_paths = [ICH_PRIOR_MASK_DIR / f'{case_id}.nii.gz' for case_id in split_df['case_id'].astype(str)]
missing_priors = [p for p in expected_prior_paths if not p.exists()]
print('ICH teacher inputs:', len(list(ICH_INPUT_DIR.glob('*.nii.gz'))))
print('Existing ICH priors:', len(expected_prior_paths) - len(missing_priors), '/', len(expected_prior_paths))

if RUN_ICH_PRIOR_PREDICT and (OVERWRITE_ICH_PRIORS or missing_priors):
    import torch
    from nnunetv2.inference.predict_from_raw_data import nnUNetPredictor
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    print('ICH teacher predict device:', device)
    predictor = nnUNetPredictor(
        tile_step_size=0.5,
        use_gaussian=True,
        use_mirroring=not ICH_DISABLE_TTA,
        perform_everything_on_device=(device.type == 'cuda'),
        device=device,
        verbose=False,
        verbose_preprocessing=False,
        allow_tqdm=True,
    )
    predictor.initialize_from_trained_model_folder(
        str(ICH_TEACHER_MODEL_DIR),
        use_folds=(ICH_TEACHER_FOLD,),
        checkpoint_name=ICH_TEACHER_CHECKPOINT,
    )
    predictor.predict_from_files(
        str(ICH_INPUT_DIR),
        str(ICH_PRIOR_MASK_DIR),
        save_probabilities=False,
        overwrite=OVERWRITE_ICH_PRIORS,
        num_processes_preprocessing=1,
        num_processes_segmentation_export=1,
        folder_with_segs_from_prev_stage=None,
        num_parts=1,
        part_id=0,
    )
elif RUN_ICH_PRIOR_PREDICT:
    print('All ICH priors already exist. Set OVERWRITE_ICH_PRIORS=True to regenerate.')
else:
    print('Skipped ICH teacher inference. Set RUN_ICH_PRIOR_PREDICT=True to run.')

print('ICH prior dir:', ICH_PRIOR_MASK_DIR)

ICH teacher inputs: 120
Existing ICH priors: 0 / 120
ICH teacher predict device: cuda
There are 120 cases in the source folder
I am process 0 out of 1 (max process ID is 0, we start counting with 0!)
There are 120 cases that I would like to predict
overwrite was set to False, so I am only working on cases that haven't been predicted yet. That's 120 cases.

Predicting phe_0001:
perform_everything_on_device: True

100%|██████████| 180/180 [01:45<00:00,  1.70it/s]

sending off prediction to background worker for resampling and export
done with phe_0001

Predicting phe_0002:
perform_everything_on_device: True

100%|██████████| 180/180 [01:44<00:00,  1.73it/s]

sending off prediction to background worker for resampling and export
done with phe_0002

Predicting phe_0004:
perform_everything_on_device: True

100%|██████████| 120/120 [01:09<00:00,  1.73it/s]

sending off prediction to background worker for resampling and export
done with phe_0004

Predicting phe_0005:
perform_everything_on_device: True

100%|██████████| 120/120 [01:09<00:00,  1.74it/s]

sending off prediction to background worker for resampling and export
done with phe_0005

Predicting phe_0006:
perform_everything_on_device: True

100%|██████████| 120/120 [01:09<00:00,  1.74it/s]

sending off prediction to background worker for resampling and export
done with phe_0006

Predicting phe_0008:
perform_everything_on_device: True

100%|██████████| 180/180 [01:44<00:00,  1.73it/s]

sending off prediction to background worker for resampling and export
done with phe_0008

Predicting phe_0009:
perform_everything_on_device: True

100%|██████████| 180/180 [01:44<00:00,  1.73it/s]

sending off prediction to background worker for resampling and export
done with phe_0009

Predicting phe_0011:
perform_everything_on_device: True

100%|██████████| 150/150 [01:26<00:00,  1.73it/s]

sending off prediction to background worker for resampling and export
done with phe_0011

Predicting phe_0012:
perform_everything_on_device: True

100%|██████████| 252/252 [02:26<00:00,  1.72it/s]

sending off prediction to background worker for resampling and export
done with phe_0012

Predicting phe_0013:
perform_everything_on_device: True

100%|██████████| 180/180 [01:44<00:00,  1.73it/s]

sending off prediction to background worker for resampling and export
done with phe_0013

Predicting phe_0014:
perform_everything_on_device: True

100%|██████████| 120/120 [01:09<00:00,  1.74it/s]

sending off prediction to background worker for resampling and export
done with phe_0014

Predicting phe_0015:
perform_everything_on_device: True

100%|██████████| 180/180 [01:43<00:00,  1.74it/s]

sending off prediction to background worker for resampling and export
done with phe_0015

Predicting phe_0016:
perform_everything_on_device: True

100%|██████████| 180/180 [01:43<00:00,  1.74it/s]

sending off prediction to background worker for resampling and export
done with phe_0016

Predicting phe_0017:
perform_everything_on_device: True

100%|██████████| 180/180 [01:43<00:00,  1.74it/s]

sending off prediction to background worker for resampling and export
done with phe_0017

Predicting phe_0018:
perform_everything_on_device: True

100%|██████████| 180/180 [01:45<00:00,  1.70it/s]

sending off prediction to background worker for resampling and export
done with phe_0018

Predicting phe_0021:
perform_everything_on_device: True

100%|██████████| 180/180 [01:48<00:00,  1.67it/s]

sending off prediction to background worker for resampling and export
done with phe_0021

Predicting phe_0022:
perform_everything_on_device: True

100%|██████████| 180/180 [01:47<00:00,  1.68it/s]

sending off prediction to background worker for resampling and export
done with phe_0022

Predicting phe_0023:
perform_everything_on_device: True

100%|██████████| 120/120 [01:11<00:00,  1.69it/s]

sending off prediction to background worker for resampling and export
done with phe_0023

Predicting phe_0024:
perform_everything_on_device: True

100%|██████████| 140/140 [01:23<00:00,  1.67it/s]

sending off prediction to background worker for resampling and export
done with phe_0024

Predicting phe_0025:
perform_everything_on_device: True

100%|██████████| 120/120 [01:11<00:00,  1.68it/s]

sending off prediction to background worker for resampling and export
done with phe_0025

Predicting phe_0026:
perform_everything_on_device: True

100%|██████████| 120/120 [01:11<00:00,  1.68it/s]

sending off prediction to background worker for resampling and export
done with phe_0026

Predicting phe_0028:
perform_everything_on_device: True

100%|██████████| 180/180 [01:48<00:00,  1.65it/s]

sending off prediction to background worker for resampling and export
done with phe_0028

Predicting phe_0029:
perform_everything_on_device: True

100%|██████████| 120/120 [01:11<00:00,  1.69it/s]

sending off prediction to background worker for resampling and export
done with phe_0029

Predicting phe_0030:
perform_everything_on_device: True

100%|██████████| 420/420 [04:12<00:00,  1.67it/s]

sending off prediction to background worker for resampling and export
done with phe_0030

Predicting phe_0031:
perform_everything_on_device: True

100%|██████████| 180/180 [01:47<00:00,  1.67it/s]

sending off prediction to background worker for resampling and export
done with phe_0031

Predicting phe_0032:
perform_everything_on_device: True

100%|██████████| 150/150 [01:30<00:00,  1.65it/s]

sending off prediction to background worker for resampling and export
done with phe_0032

Predicting phe_0033:
perform_everything_on_device: True

100%|██████████| 180/180 [01:47<00:00,  1.68it/s]

sending off prediction to background worker for resampling and export
done with phe_0033

Predicting phe_0034:
perform_everything_on_device: True

100%|██████████| 210/210 [02:06<00:00,  1.66it/s]

sending off prediction to background worker for resampling and export
done with phe_0034

Predicting phe_0035:
perform_everything_on_device: True

100%|██████████| 180/180 [01:47<00:00,  1.67it/s]

sending off prediction to background worker for resampling and export
done with phe_0035

Predicting phe_0036:
perform_everything_on_device: True

100%|██████████| 180/180 [01:47<00:00,  1.67it/s]

sending off prediction to background worker for resampling and export
done with phe_0036

Predicting phe_0037:
perform_everything_on_device: True

100%|██████████| 180/180 [01:47<00:00,  1.68it/s]

sending off prediction to background worker for resampling and export
done with phe_0037

Predicting phe_0038:
perform_everything_on_device: True

100%|██████████| 784/784 [07:52<00:00,  1.66it/s]

sending off prediction to background worker for resampling and export
done with phe_0038

Predicting phe_0039:
perform_everything_on_device: True

100%|██████████| 80/80 [00:47<00:00,  1.69it/s]

sending off prediction to background worker for resampling and export
done with phe_0039

Predicting phe_0040:
perform_everything_on_device: True

100%|██████████| 120/120 [01:12<00:00,  1.66it/s]

sending off prediction to background worker for resampling and export
done with phe_0040

Predicting phe_0041:
perform_everything_on_device: True

100%|██████████| 210/210 [02:04<00:00,  1.68it/s]

sending off prediction to background worker for resampling and export
done with phe_0041

Predicting phe_0042:
perform_everything_on_device: True

100%|██████████| 120/120 [01:09<00:00,  1.73it/s]

sending off prediction to background worker for resampling and export
done with phe_0042

Predicting phe_0043:
perform_everything_on_device: True

100%|██████████| 210/210 [02:04<00:00,  1.68it/s]

sending off prediction to background worker for resampling and export
done with phe_0043

Predicting phe_0044:
perform_everything_on_device: True

100%|██████████| 120/120 [01:10<00:00,  1.70it/s]

sending off prediction to background worker for resampling and export
done with phe_0044

Predicting phe_0045:
perform_everything_on_device: True

100%|██████████| 150/150 [01:31<00:00,  1.63it/s]

sending off prediction to background worker for resampling and export
done with phe_0045

Predicting phe_0046:
perform_everything_on_device: True

100%|██████████| 120/120 [01:12<00:00,  1.66it/s]

sending off prediction to background worker for resampling and export
done with phe_0046

Predicting phe_0048:
perform_everything_on_device: True

100%|██████████| 120/120 [01:12<00:00,  1.67it/s]

sending off prediction to background worker for resampling and export
done with phe_0048

Predicting phe_0049:
perform_everything_on_device: True

100%|██████████| 120/120 [01:11<00:00,  1.67it/s]

sending off prediction to background worker for resampling and export
done with phe_0049

Predicting phe_0051:
perform_everything_on_device: True

100%|██████████| 120/120 [01:11<00:00,  1.67it/s]

sending off prediction to background worker for resampling and export
done with phe_0051

Predicting phe_0052:
perform_everything_on_device: True

100%|██████████| 150/150 [01:29<00:00,  1.68it/s]

sending off prediction to background worker for resampling and export
done with phe_0052

Predicting phe_0053:
perform_everything_on_device: True

100%|██████████| 180/180 [01:48<00:00,  1.66it/s]

sending off prediction to background worker for resampling and export
done with phe_0053

Predicting phe_0055:
perform_everything_on_device: True

100%|██████████| 120/120 [01:11<00:00,  1.67it/s]

sending off prediction to background worker for resampling and export
done with phe_0055

Predicting phe_0056:
perform_everything_on_device: True

100%|██████████| 80/80 [00:47<00:00,  1.69it/s]

sending off prediction to background worker for resampling and export
done with phe_0056

Predicting phe_0057:
perform_everything_on_device: True

100%|██████████| 150/150 [01:29<00:00,  1.67it/s]

sending off prediction to background worker for resampling and export
done with phe_0057

Predicting phe_0058:
perform_everything_on_device: True

100%|██████████| 120/120 [01:12<00:00,  1.65it/s]

sending off prediction to background worker for resampling and export
done with phe_0058

Predicting phe_0059:
perform_everything_on_device: True

100%|██████████| 180/180 [01:49<00:00,  1.64it/s]

sending off prediction to background worker for resampling and export
done with phe_0059

Predicting phe_0060:
perform_everything_on_device: True

100%|██████████| 180/180 [01:45<00:00,  1.71it/s]

sending off prediction to background worker for resampling and export
done with phe_0060

Predicting phe_0061:
perform_everything_on_device: True

100%|██████████| 120/120 [01:09<00:00,  1.73it/s]

sending off prediction to background worker for resampling and export
done with phe_0061

Predicting phe_0064:
perform_everything_on_device: True

100%|██████████| 120/120 [01:09<00:00,  1.74it/s]

sending off prediction to background worker for resampling and export
done with phe_0064

Predicting phe_0065:
perform_everything_on_device: True

100%|██████████| 120/120 [01:09<00:00,  1.73it/s]

sending off prediction to background worker for resampling and export
done with phe_0065

Predicting phe_0066:
perform_everything_on_device: True

100%|██████████| 120/120 [01:09<00:00,  1.73it/s]

sending off prediction to background worker for resampling and export
done with phe_0066

Predicting phe_0067:
perform_everything_on_device: True

100%|██████████| 80/80 [00:45<00:00,  1.74it/s]

sending off prediction to background worker for resampling and export
done with phe_0067

Predicting phe_0068:
perform_everything_on_device: True

100%|██████████| 180/180 [01:47<00:00,  1.67it/s]

sending off prediction to background worker for resampling and export
done with phe_0068

Predicting phe_0069:
perform_everything_on_device: True

100%|██████████| 150/150 [01:29<00:00,  1.68it/s]

sending off prediction to background worker for resampling and export
done with phe_0069

Predicting phe_0070:
perform_everything_on_device: True

100%|██████████| 120/120 [01:09<00:00,  1.74it/s]

sending off prediction to background worker for resampling and export
done with phe_0070

Predicting phe_0071:
perform_everything_on_device: True

100%|██████████| 120/120 [01:09<00:00,  1.74it/s]

sending off prediction to background worker for resampling and export
done with phe_0071

Predicting phe_0073:
perform_everything_on_device: True

100%|██████████| 120/120 [01:09<00:00,  1.73it/s]

sending off prediction to background worker for resampling and export
done with phe_0073

Predicting phe_0074:
perform_everything_on_device: True

100%|██████████| 120/120 [01:09<00:00,  1.72it/s]

sending off prediction to background worker for resampling and export
done with phe_0074

Predicting phe_0075:
perform_everything_on_device: True

100%|██████████| 80/80 [00:46<00:00,  1.73it/s]

sending off prediction to background worker for resampling and export
done with phe_0075

Predicting phe_0076:
perform_everything_on_device: True

100%|██████████| 120/120 [01:09<00:00,  1.72it/s]

sending off prediction to background worker for resampling and export
done with phe_0076

Predicting phe_0077:
perform_everything_on_device: True

100%|██████████| 120/120 [01:08<00:00,  1.74it/s]

sending off prediction to background worker for resampling and export
done with phe_0077

Predicting phe_0078:
perform_everything_on_device: True

100%|██████████| 120/120 [01:10<00:00,  1.71it/s]

sending off prediction to background worker for resampling and export
done with phe_0078

Predicting phe_0080:
perform_everything_on_device: True

100%|██████████| 180/180 [01:47<00:00,  1.68it/s]

sending off prediction to background worker for resampling and export
done with phe_0080

Predicting phe_0081:
perform_everything_on_device: True

100%|██████████| 150/150 [01:29<00:00,  1.67it/s]

sending off prediction to background worker for resampling and export
done with phe_0081

Predicting phe_0083:
perform_everything_on_device: True

100%|██████████| 120/120 [01:10<00:00,  1.71it/s]

sending off prediction to background worker for resampling and export
done with phe_0083

Predicting phe_0084:
perform_everything_on_device: True

100%|██████████| 180/180 [01:44<00:00,  1.72it/s]

sending off prediction to background worker for resampling and export
done with phe_0084

Predicting phe_0086:
perform_everything_on_device: True

100%|██████████| 150/150 [01:29<00:00,  1.67it/s]

sending off prediction to background worker for resampling and export
done with phe_0086

Predicting phe_0087:
perform_everything_on_device: True

100%|██████████| 180/180 [01:47<00:00,  1.67it/s]

sending off prediction to background worker for resampling and export
done with phe_0087

Predicting phe_0088:
perform_everything_on_device: True

100%|██████████| 80/80 [00:47<00:00,  1.69it/s]

sending off prediction to background worker for resampling and export
done with phe_0088

Predicting phe_0090:
perform_everything_on_device: True

100%|██████████| 120/120 [01:11<00:00,  1.68it/s]

sending off prediction to background worker for resampling and export
done with phe_0090

Predicting phe_0092:
perform_everything_on_device: True

100%|██████████| 120/120 [01:11<00:00,  1.68it/s]

sending off prediction to background worker for resampling and export
done with phe_0092

Predicting phe_0093:
perform_everything_on_device: True

100%|██████████| 120/120 [01:11<00:00,  1.68it/s]

sending off prediction to background worker for resampling and export
done with phe_0093

Predicting phe_0095:
perform_everything_on_device: True

100%|██████████| 252/252 [02:31<00:00,  1.67it/s]

sending off prediction to background worker for resampling and export
done with phe_0095

Predicting phe_0096:
perform_everything_on_device: True

100%|██████████| 150/150 [01:29<00:00,  1.68it/s]

sending off prediction to background worker for resampling and export
done with phe_0096

Predicting phe_0097:
perform_everything_on_device: True

100%|██████████| 150/150 [01:31<00:00,  1.64it/s]

sending off prediction to background worker for resampling and export
done with phe_0097

Predicting phe_0098:
perform_everything_on_device: True

100%|██████████| 100/100 [01:00<00:00,  1.66it/s]

sending off prediction to background worker for resampling and export
done with phe_0098

Predicting phe_0099:
perform_everything_on_device: True

100%|██████████| 120/120 [01:11<00:00,  1.67it/s]

sending off prediction to background worker for resampling and export
done with phe_0099

Predicting phe_0100:
perform_everything_on_device: True

100%|██████████| 80/80 [00:47<00:00,  1.68it/s]

sending off prediction to background worker for resampling and export
done with phe_0100

Predicting phe_0101:
perform_everything_on_device: True

100%|██████████| 120/120 [01:12<00:00,  1.66it/s]

sending off prediction to background worker for resampling and export
done with phe_0101

Predicting phe_0102:
perform_everything_on_device: True

100%|██████████| 120/120 [01:12<00:00,  1.67it/s]

sending off prediction to background worker for resampling and export
done with phe_0102

Predicting phe_0103:
perform_everything_on_device: True

100%|██████████| 120/120 [01:09<00:00,  1.73it/s]

sending off prediction to background worker for resampling and export
done with phe_0103

Predicting phe_0104:
perform_everything_on_device: True

100%|██████████| 80/80 [00:46<00:00,  1.74it/s]

sending off prediction to background worker for resampling and export
done with phe_0104

Predicting phe_0106:
perform_everything_on_device: True

100%|██████████| 120/120 [01:09<00:00,  1.72it/s]

sending off prediction to background worker for resampling and export
done with phe_0106

Predicting phe_0108:
perform_everything_on_device: True

100%|██████████| 120/120 [01:09<00:00,  1.72it/s]

sending off prediction to background worker for resampling and export
done with phe_0108

Predicting phe_0112:
perform_everything_on_device: True

100%|██████████| 120/120 [01:09<00:00,  1.73it/s]

sending off prediction to background worker for resampling and export
done with phe_0112

Predicting phe_0113:
perform_everything_on_device: True

100%|██████████| 120/120 [01:12<00:00,  1.67it/s]

sending off prediction to background worker for resampling and export
done with phe_0113

Predicting phe_0115:
perform_everything_on_device: True

100%|██████████| 210/210 [02:06<00:00,  1.66it/s]

sending off prediction to background worker for resampling and export
done with phe_0115

Predicting phe_0116:
perform_everything_on_device: True

100%|██████████| 180/180 [01:46<00:00,  1.70it/s]

sending off prediction to background worker for resampling and export
done with phe_0116

Predicting phe_0118:
perform_everything_on_device: True

100%|██████████| 100/100 [00:57<00:00,  1.75it/s]

sending off prediction to background worker for resampling and export
done with phe_0118

Predicting phe_0119:
perform_everything_on_device: True

100%|██████████| 150/150 [01:26<00:00,  1.74it/s]

sending off prediction to background worker for resampling and export
done with phe_0119

Predicting phe_0124:
perform_everything_on_device: True

100%|██████████| 120/120 [01:08<00:00,  1.75it/s]

sending off prediction to background worker for resampling and export
done with phe_0124

Predicting phe_0125:
perform_everything_on_device: True

100%|██████████| 210/210 [02:05<00:00,  1.67it/s]

sending off prediction to background worker for resampling and export
done with phe_0125

Predicting phe_0126:
perform_everything_on_device: True

100%|██████████| 150/150 [01:28<00:00,  1.69it/s]

sending off prediction to background worker for resampling and export
done with phe_0126

Predicting phe_0129:
perform_everything_on_device: True

100%|██████████| 120/120 [01:11<00:00,  1.68it/s]

sending off prediction to background worker for resampling and export
done with phe_0129

Predicting phe_0130:
perform_everything_on_device: True

100%|██████████| 120/120 [01:11<00:00,  1.67it/s]

sending off prediction to background worker for resampling and export
done with phe_0130

Predicting phe_0131:
perform_everything_on_device: True

100%|██████████| 80/80 [00:47<00:00,  1.69it/s]

sending off prediction to background worker for resampling and export
done with phe_0131

Predicting phe_0132:
perform_everything_on_device: True

100%|██████████| 120/120 [01:11<00:00,  1.68it/s]

sending off prediction to background worker for resampling and export
done with phe_0132

Predicting phe_0133:
perform_everything_on_device: True

100%|██████████| 80/80 [00:47<00:00,  1.69it/s]

sending off prediction to background worker for resampling and export
done with phe_0133

Predicting phe_0134:
perform_everything_on_device: True

100%|██████████| 168/168 [01:41<00:00,  1.66it/s]

sending off prediction to background worker for resampling and export
done with phe_0134

Predicting phe_0135:
perform_everything_on_device: True

100%|██████████| 150/150 [01:29<00:00,  1.68it/s]

sending off prediction to background worker for resampling and export
done with phe_0135

Predicting phe_0136:
perform_everything_on_device: True

100%|██████████| 120/120 [01:09<00:00,  1.73it/s]

sending off prediction to background worker for resampling and export
done with phe_0136

Predicting phe_0138:
perform_everything_on_device: True

100%|██████████| 120/120 [01:10<00:00,  1.70it/s]

sending off prediction to background worker for resampling and export
done with phe_0138

Predicting phe_0139:
perform_everything_on_device: True

100%|██████████| 120/120 [01:11<00:00,  1.68it/s]

sending off prediction to background worker for resampling and export
done with phe_0139

Predicting phe_0140:
perform_everything_on_device: True

100%|██████████| 120/120 [01:10<00:00,  1.70it/s]

sending off prediction to background worker for resampling and export
done with phe_0140

Predicting phe_0141:
perform_everything_on_device: True

100%|██████████| 120/120 [01:09<00:00,  1.73it/s]

sending off prediction to background worker for resampling and export
done with phe_0141

Predicting phe_0142:
perform_everything_on_device: True

100%|██████████| 120/120 [01:09<00:00,  1.73it/s]

sending off prediction to background worker for resampling and export
done with phe_0142

Predicting phe_0144:
perform_everything_on_device: True

100%|██████████| 180/180 [01:43<00:00,  1.74it/s]

sending off prediction to background worker for resampling and export
done with phe_0144

Predicting phe_0146:
perform_everything_on_device: True

100%|██████████| 120/120 [01:08<00:00,  1.75it/s]

sending off prediction to background worker for resampling and export
done with phe_0146

Predicting phe_0160:
perform_everything_on_device: True

100%|██████████| 80/80 [00:45<00:00,  1.76it/s]

sending off prediction to background worker for resampling and export
done with phe_0160

Predicting phe_0161:
perform_everything_on_device: True

100%|██████████| 180/180 [01:43<00:00,  1.74it/s]

sending off prediction to background worker for resampling and export
done with phe_0161

Predicting phe_0162:
perform_everything_on_device: True

100%|██████████| 120/120 [01:08<00:00,  1.75it/s]

sending off prediction to background worker for resampling and export
done with phe_0162

Predicting phe_0163:
perform_everything_on_device: True

100%|██████████| 728/728 [07:16<00:00,  1.67it/s]

sending off prediction to background worker for resampling and export
done with phe_0163

Predicting phe_0164:
perform_everything_on_device: True

100%|██████████| 180/180 [01:43<00:00,  1.74it/s]

sending off prediction to background worker for resampling and export
done with phe_0164

Predicting phe_0165:
perform_everything_on_device: True

100%|██████████| 120/120 [01:08<00:00,  1.75it/s]

sending off prediction to background worker for resampling and export
done with phe_0165

Predicting phe_0166:
perform_everything_on_device: True

100%|██████████| 180/180 [01:43<00:00,  1.74it/s]

sending off prediction to background worker for resampling and export
done with phe_0166

Predicting phe_0167:
perform_everything_on_device: True

100%|██████████| 120/120 [01:08<00:00,  1.75it/s]

sending off prediction to background worker for resampling and export
done with phe_0167
GPU prediction completed. Waiting for remaining segmentation exports to finish...

Collecting results: 100%|██████████| 120/120 [00:04<00:00, 27.14it/s]

Segmentation export complete.
ICH prior dir: D:\Thuy_Loi\Nam_3\CT_xuathuyetnao\outputs_02_14_nnunet_phe_ich_teacher_prior\ich_teacher_prior_masks

## 3. Quick inspect ICH prior

In [5]:
INSPECT_PRIORS = True
MAX_INSPECT = 8

if INSPECT_PRIORS:
    inspect_rows = []
    for row in split_df.head(MAX_INSPECT).itertuples(index=False):
        case_id = str(row.case_id)
        prior_path = ICH_PRIOR_MASK_DIR / f'{case_id}.nii.gz'
        if not prior_path.exists():
            inspect_rows.append({'case_id': case_id, 'split': row.split, 'status': 'missing'})
            continue
        img = sitk.ReadImage(str(prior_path))
        arr = sitk.GetArrayFromImage(img)
        inspect_rows.append({
            'case_id': case_id,
            'split': row.split,
            'status': 'ok',
            'shape_zyx': tuple(arr.shape),
            'unique_values': np.unique(arr).tolist(),
            'ich_prior_voxels': int((arr > 0).sum()),
        })
    display(pd.DataFrame(inspect_rows))
else:
    print('Skipped prior inspection.')

    case_id  split status       shape_zyx unique_values  ich_prior_voxels
0  phe_0001  train     ok  (32, 512, 512)        [0, 1]              8734
1  phe_0002   test     ok  (32, 512, 512)        [0, 1]              1351
2  phe_0004  train     ok  (32, 512, 512)        [0, 1]             14098
3  phe_0005  train     ok  (32, 512, 512)        [0, 1]              5509
4  phe_0006  train     ok  (32, 512, 512)        [0, 1]             38815
5  phe_0008  train     ok  (32, 512, 512)        [0, 1]             17165
6  phe_0009  train     ok  (32, 512, 512)        [0, 1]              3949
7  phe_0011  train     ok  (30, 512, 512)        [0, 1]              5161

## 4. Convert PHE-SICH to 2-channel nnU-Net raw dataset

Raw dataset moi se co:

```text
imagesTr/phe_xxxx_0000.nii.gz  # CT
imagesTr/phe_xxxx_0001.nii.gz  # ICH teacher prior mask
labelsTr/phe_xxxx.nii.gz       # manual PHE
```

In [6]:
OVERWRITE_RAW_DATASET = True

def write_binary_like_reference(src_path: Path, reference_path: Path, dst_path: Path):
    src_path = Path(src_path)
    reference_path = Path(reference_path)
    dst_path = Path(dst_path)
    ref = sitk.ReadImage(str(reference_path))
    seg = sitk.ReadImage(str(src_path))
    arr = sitk.GetArrayFromImage(seg)
    out = sitk.GetImageFromArray((arr > 0).astype(np.uint8))
    if ref.GetSize() != out.GetSize():
        raise ValueError(f'Size mismatch: reference {reference_path} {ref.GetSize()} vs {src_path} {out.GetSize()}')
    out.CopyInformation(ref)
    sitk.WriteImage(out, str(dst_path))

if DATASET_DIR.exists() and OVERWRITE_RAW_DATASET:
    shutil.rmtree(DATASET_DIR)

imagesTr = DATASET_DIR / 'imagesTr'
labelsTr = DATASET_DIR / 'labelsTr'
imagesTs = DATASET_DIR / 'imagesTs'
labelsTs = DATASET_DIR / 'labelsTs'
for p in [imagesTr, labelsTr, imagesTs, labelsTs]:
    p.mkdir(parents=True, exist_ok=True)

records = []
for row in split_df.itertuples(index=False):
    case_id = str(row.case_id)
    img_src = Path(row.img_path)
    phe_src = Path(row.phe_mask_path)
    ich_prior_src = ICH_PRIOR_MASK_DIR / f'{case_id}.nii.gz'
    assert ich_prior_src.exists(), f'Missing ICH prior for {case_id}: {ich_prior_src}'

    if row.split == 'test':
        img_dst = imagesTs / f'{case_id}_0000.nii.gz'
        prior_dst = imagesTs / f'{case_id}_0001.nii.gz'
        seg_dst = labelsTs / f'{case_id}.nii.gz'
    else:
        img_dst = imagesTr / f'{case_id}_0000.nii.gz'
        prior_dst = imagesTr / f'{case_id}_0001.nii.gz'
        seg_dst = labelsTr / f'{case_id}.nii.gz'

    shutil.copy2(img_src, img_dst)
    write_binary_like_reference(ich_prior_src, img_dst, prior_dst)
    write_binary_like_reference(phe_src, img_dst, seg_dst)
    records.append({
        'case_id': case_id,
        'split': row.split,
        'ct_channel': str(img_dst),
        'ich_prior_channel': str(prior_dst),
        'phe_label': str(seg_dst),
        'source_image': str(img_src),
        'source_phe_mask': str(phe_src),
        'source_ich_prior': str(ich_prior_src),
    })

dataset_json = {
    'channel_names': {'0': 'CT', '1': 'ICH_teacher_prior'},
    'labels': {'background': 0, 'PHE': 1},
    'numTraining': int((split_df['split'] != 'test').sum()),
    'file_ending': '.nii.gz',
    'overwrite_image_reader_writer': 'SimpleITKIO',
}
with open(DATASET_DIR / 'dataset.json', 'w', encoding='utf-8') as f:
    json.dump(dataset_json, f, indent=2)

conversion_df = pd.DataFrame(records)
conversion_df.to_csv(OUTPUT_ROOT / '02_14_nnunet_phe_ich_prior_conversion_manifest.csv', index=False)

print('Dataset dir:', DATASET_DIR)
print('imagesTr channel files:', len(list(imagesTr.glob('*.nii.gz'))))
print('labelsTr:', len(list(labelsTr.glob('*.nii.gz'))))
print('imagesTs channel files:', len(list(imagesTs.glob('*.nii.gz'))))
print('labelsTs:', len(list(labelsTs.glob('*.nii.gz'))))
print('dataset.json:', DATASET_DIR / 'dataset.json')
display(conversion_df.groupby('split').size().rename('cases').reset_index())

Dataset dir: D:\Thuy_Loi\Nam_3\CT_xuathuyetnao\outputs_02_14_nnunet_phe_ich_teacher_prior\nnunet_workdir\nnUNet_raw\Dataset114_PHESICH_PHE_ICHTeacherPrior
imagesTr channel files: 218
labelsTr: 109
imagesTs channel files: 22
labelsTs: 11
dataset.json: D:\Thuy_Loi\Nam_3\CT_xuathuyetnao\outputs_02_14_nnunet_phe_ich_teacher_prior\nnunet_workdir\nnUNet_raw\Dataset114_PHESICH_PHE_ICHTeacherPrior\dataset.json

   split  cases
0   test     11
1  train     99
2    val     10

## 5. Helper call entrypoints

In [7]:
def call_entrypoint(entrypoint_func, argv):
    old_argv = sys.argv[:]
    sys.argv = list(argv)
    print('>>>', ' '.join(map(str, sys.argv)))
    t0 = time.time()
    try:
        return entrypoint_func()
    finally:
        sys.argv = old_argv
        print(f'Done in {(time.time() - t0) / 60:.1f} min')

## 6. Plan and preprocess Dataset114

In [8]:
CONFIGURATION = '3d_fullres'
RUN_PLAN_PREPROCESS = True

if RUN_PLAN_PREPROCESS:
    from nnunetv2.experiment_planning.plan_and_preprocess_entrypoints import plan_and_preprocess_entry
    old_n_proc_da = os.environ.get('nnUNet_n_proc_DA')
    os.environ['nnUNet_n_proc_DA'] = '1'
    try:
        call_entrypoint(plan_and_preprocess_entry, [
            'nnUNetv2_plan_and_preprocess',
            '-d', str(DATASET_ID),
            '-c', CONFIGURATION,
            '--verify_dataset_integrity',
            '-npfp', '2',
            '-np', '1',
        ])
    finally:
        os.environ['nnUNet_n_proc_DA'] = old_n_proc_da if old_n_proc_da is not None else '0'
else:
    print('Skipped. Set RUN_PLAN_PREPROCESS=True to run.')

>>> nnUNetv2_plan_and_preprocess -d 114 -c 3d_fullres --verify_dataset_integrity -npfp 2 -np 1
Fingerprint extraction...
Dataset114_PHESICH_PHE_ICHTeacherPrior
Using <class 'nnunetv2.imageio.simpleitk_reader_writer.SimpleITKIO'> reader/writer

####################
verify_dataset_integrity Done.
If you didn't see any error messages then your dataset is most likely OK!
####################

Using <class 'nnunetv2.imageio.simpleitk_reader_writer.SimpleITKIO'> reader/writer

Extracting dataset fingerprint: 100%|██████████| 109/109 [00:16<00:00,  6.65it/s]

Experiment planning...

############################
INFO: You are using the old nnU-Net default planner. We have updated our recommendations. Please consider using those instead! Read more here: https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/resenc_presets.md
############################

Attempting to find 3d_lowres config.
Current spacing: [5.         0.50292969 0.50292969].
Current patch size: (16, 320, 320).
Current median shape: [ 30.         497.08737864 497.08737864]
Attempting to find 3d_lowres config.
Current spacing: [5.         0.51801758 0.51801758].
Current patch size: (16, 320, 320).
Current median shape: [ 30.         482.60910548 482.60910548]
Attempting to find 3d_lowres config.
Current spacing: [5.         0.53355811 0.53355811].
Current patch size: (20, 320, 256).
Current median shape: [ 30.         468.55252959 468.55252959]
Attempting to find 3d_lowres config.
Current spacing: [5.         0.54956485 0.54956485].
Current patch size: (20, 320, 256).
Current median shape: [ 30.         454.90536853 454.90536853]
Dropping 3d_lowres config because the image size difference to 3d_fullres is too small. 3d_fullres: [ 30. 512. 512.], 3d_lowres: [30, 455, 455]
2D U-Net configuration:
{'data_identifier': 'nnUNetPlans_2d', 'preprocessor_name': 'DefaultPreprocessor', 'batch_size': 12, 'patch_size': (512, 512), 'median_image_size_in_voxels': array([512., 512.]), 'spacing': array([0.48828125, 0.48828125]), 'normalization_schemes': ['CTNormalization', 'ZScoreNormalization'], 'use_mask_for_norm': [False, False], 'resampling_fn_data': 'resample_data_or_seg_to_shape', 'resampling_fn_seg': 'resample_data_or_seg_to_shape', 'resampling_fn_data_kwargs': {'is_seg': False, 'order': 3, 'order_z': 0, 'force_separate_z': None}, 'resampling_fn_seg_kwargs': {'is_seg': True, 'order': 1, 'order_z': 0, 'force_separate_z': None}, 'resampling_fn_probabilities': 'resample_data_or_seg_to_shape', 'resampling_fn_probabilities_kwargs': {'is_seg': False, 'order': 1, 'order_z': 0, 'force_separate_z': None}, 'architecture': {'network_class_name': 'dynamic_network_architectures.architectures.unet.PlainConvUNet', 'arch_kwargs': {'n_stages': 8, 'features_per_stage': (32, 64, 128, 256, 512, 512, 512, 512), 'conv_op': 'torch.nn.modules.conv.Conv2d', 'kernel_sizes': ((3, 3), (3, 3), (3, 3), (3, 3), (3, 3), (3, 3), (3, 3), (3, 3)), 'strides': ((1, 1), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2)), 'n_conv_per_stage': (2, 2, 2, 2, 2, 2, 2, 2), 'n_conv_per_stage_decoder': (2, 2, 2, 2, 2, 2, 2), 'conv_bias': True, 'norm_op': 'torch.nn.modules.instancenorm.InstanceNorm2d', 'norm_op_kwargs': {'eps': 1e-05, 'affine': True}, 'dropout_op': None, 'dropout_op_kwargs': None, 'nonlin': 'torch.nn.LeakyReLU', 'nonlin_kwargs': {'inplace': True}}, '_kw_requires_import': ('conv_op', 'norm_op', 'dropout_op', 'nonlin')}, 'batch_dice': True}

Using <class 'nnunetv2.imageio.simpleitk_reader_writer.SimpleITKIO'> reader/writer
3D fullres U-Net configuration:
{'data_identifier': 'nnUNetPlans_3d_fullres', 'preprocessor_name': 'DefaultPreprocessor', 'batch_size': 2, 'patch_size': (16, 320, 320), 'median_image_size_in_voxels': array([ 30., 512., 512.]), 'spacing': array([5.        , 0.48828125, 0.48828125]), 'normalization_schemes': ['CTNormalization', 'ZScoreNormalization'], 'use_mask_for_norm': [False, False], 'resampling_fn_data': 'resample_data_or_seg_to_shape', 'resampling_fn_seg': 'resample_data_or_seg_to_shape', 'resampling_fn_data_kwargs': {'is_seg': False, 'order': 3, 'order_z': 0, 'force_separate_z': None}, 'resampling_fn_seg_kwargs': {'is_seg': True, 'order': 1, 'order_z': 0, 'force_separate_z': None}, 'resampling_fn_probabilities': 'resample_data_or_seg_to_shape', 'resampling_fn_probabilities_kwargs': {'is_seg': False, 'order': 1, 'order_z': 0, 'force_separate_z': None}, 'architecture': {'network_class_name': 'dynamic_network_architectures.architectures.unet.PlainConvUNet', 'arch_kwargs': {'n_stages': 7, 'features_per_stage': (32, 64, 128, 256, 320, 320, 320), 'conv_op': 'torch.nn.modules.conv.Conv3d', 'kernel_sizes': ((1, 3, 3), (1, 3, 3), (1, 3, 3), (3, 3, 3), (3, 3, 3), (3, 3, 3), (3, 3, 3)), 'strides': ((1, 1, 1), (1, 2, 2), (1, 2, 2), (1, 2, 2), (2, 2, 2), (2, 2, 2), (1, 2, 2)), 'n_conv_per_stage': (2, 2, 2, 2, 2, 2, 2), 'n_conv_per_stage_decoder': (2, 2, 2, 2, 2, 2), 'conv_bias': True, 'norm_op': 'torch.nn.modules.instancenorm.InstanceNorm3d', 'norm_op_kwargs': {'eps': 1e-05, 'affine': True}, 'dropout_op': None, 'dropout_op_kwargs': None, 'nonlin': 'torch.nn.LeakyReLU', 'nonlin_kwargs': {'inplace': True}}, '_kw_requires_import': ('conv_op', 'norm_op', 'dropout_op', 'nonlin')}, 'batch_dice': False}

Plans were saved to D:\Thuy_Loi\Nam_3\CT_xuathuyetnao\outputs_02_14_nnunet_phe_ich_teacher_prior\nnunet_workdir\nnUNet_preprocessed\Dataset114_PHESICH_PHE_ICHTeacherPrior\nnUNetPlans.json
Preprocessing...
Preprocessing dataset Dataset114_PHESICH_PHE_ICHTeacherPrior
Configuration: 3d_fullres...
{'data_identifier': 'nnUNetPlans_3d_fullres', 'preprocessor_name': 'DefaultPreprocessor', 'batch_size': 2, 'patch_size': [16, 320, 320], 'median_image_size_in_voxels': [30.0, 512.0, 512.0], 'spacing': [5.0, 0.48828125, 0.48828125], 'normalization_schemes': ['CTNormalization', 'ZScoreNormalization'], 'use_mask_for_norm': [False, False], 'resampling_fn_data': 'resample_data_or_seg_to_shape', 'resampling_fn_seg': 'resample_data_or_seg_to_shape', 'resampling_fn_data_kwargs': {'is_seg': False, 'order': 3, 'order_z': 0, 'force_separate_z': None}, 'resampling_fn_seg_kwargs': {'is_seg': True, 'order': 1, 'order_z': 0, 'force_separate_z': None}, 'resampling_fn_probabilities': 'resample_data_or_seg_to_shape', 'resampling_fn_probabilities_kwargs': {'is_seg': False, 'order': 1, 'order_z': 0, 'force_separate_z': None}, 'architecture': {'network_class_name': 'dynamic_network_architectures.architectures.unet.PlainConvUNet', 'arch_kwargs': {'n_stages': 7, 'features_per_stage': [32, 64, 128, 256, 320, 320, 320], 'conv_op': 'torch.nn.modules.conv.Conv3d', 'kernel_sizes': [[1, 3, 3], [1, 3, 3], [1, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3]], 'strides': [[1, 1, 1], [1, 2, 2], [1, 2, 2], [1, 2, 2], [2, 2, 2], [2, 2, 2], [1, 2, 2]], 'n_conv_per_stage': [2, 2, 2, 2, 2, 2, 2], 'n_conv_per_stage_decoder': [2, 2, 2, 2, 2, 2], 'conv_bias': True, 'norm_op': 'torch.nn.modules.instancenorm.InstanceNorm3d', 'norm_op_kwargs': {'eps': 1e-05, 'affine': True}, 'dropout_op': None, 'dropout_op_kwargs': None, 'nonlin': 'torch.nn.LeakyReLU', 'nonlin_kwargs': {'inplace': True}}, '_kw_requires_import': ['conv_op', 'norm_op', 'dropout_op', 'nonlin']}, 'batch_dice': False}

Preprocessing cases: 100%|██████████| 109/109 [02:53<00:00,  1.60s/it]

Done in 3.6 min

## 7. Write manual fold-0 split

In [9]:
preprocessed_dataset_dir = NNUNET_PREPROCESSED / DATASET_NAME
split_json_path = preprocessed_dataset_dir / 'splits_final.json'

train_ids = split_df.loc[split_df['split'] == 'train', 'case_id'].astype(str).tolist()
val_ids = split_df.loc[split_df['split'] == 'val', 'case_id'].astype(str).tolist()
test_ids = split_df.loc[split_df['split'] == 'test', 'case_id'].astype(str).tolist()

manual_splits = [{'train': train_ids, 'val': val_ids}]

if preprocessed_dataset_dir.exists():
    with open(split_json_path, 'w', encoding='utf-8') as f:
        json.dump(manual_splits, f, indent=2)
    print('Wrote:', split_json_path)
    print('train:', len(train_ids), 'val:', len(val_ids), 'test:', len(test_ids))
else:
    print('Preprocessed folder not found yet:', preprocessed_dataset_dir)
    print('Run plan/preprocess first, then rerun this cell.')

Wrote: D:\Thuy_Loi\Nam_3\CT_xuathuyetnao\outputs_02_14_nnunet_phe_ich_teacher_prior\nnunet_workdir\nnUNet_preprocessed\Dataset114_PHESICH_PHE_ICHTeacherPrior\splits_final.json
train: 99 val: 10 test: 11

## 8. Train PHE model with ICH prior

Day la phan train moi cho PHE. ICH teacher van giu nguyen, khong train lai.

In [10]:
RUN_TRAIN = True
FOLD = 0
TRAINER = 'nnUNetTrainer_250epochs'
PLANS = 'nnUNetPlans'
EXPORT_VAL_NPZ = True
CONTINUE_TRAINING = True

if RUN_TRAIN:
    import torch
    from nnunetv2.run.run_training import run_training
    os.environ['nnUNet_n_proc_DA'] = '0'
    os.environ['nnUNet_compile'] = 'False'
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    print('Training device:', device)
    print('nnUNet_n_proc_DA:', os.environ.get('nnUNet_n_proc_DA'))
    print('nnUNet_compile:', os.environ.get('nnUNet_compile'))
    run_training(
        str(DATASET_ID),
        CONFIGURATION,
        str(FOLD),
        trainer_class_name=TRAINER,
        plans_identifier=PLANS,
        export_validation_probabilities=EXPORT_VAL_NPZ,
        continue_training=CONTINUE_TRAINING,
        device=device,
    )
else:
    print('Skipped. Set RUN_TRAIN=True to train.')

Training device: cuda
nnUNet_n_proc_DA: 0
nnUNet_compile: False

############################
INFO: You are using the old nnU-Net default plans. We have updated our recommendations. Please consider using those instead! Read more here: https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/resenc_presets.md
############################

Using device: cuda:0

#######################################################################
Please cite the following paper when using nnU-Net:
Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
#######################################################################

WARNING: Cannot continue training because there seems to be no checkpoint available to continue from. Starting a new training...
2026-06-17 16:49:46.400275: do_dummy_2d_data_aug: True
2026-06-17 16:49:46.401269: Using splits from existing split file: D:\Thuy_Loi\Nam_3\CT_xuathuyetnao\outputs_02_14_nnunet_phe_ich_teacher_prior\nnunet_workdir\nnUNet_preprocessed\Dataset114_PHESICH_PHE_ICHTeacherPrior\splits_final.json
2026-06-17 16:49:46.401269: The split file contains 1 splits.
2026-06-17 16:49:46.401269: Desired fold for training: 0
2026-06-17 16:49:46.401269: This split has 99 training and 10 validation cases.

This is the configuration used by this training:
Configuration name: 3d_fullres
 {'data_identifier': 'nnUNetPlans_3d_fullres', 'preprocessor_name': 'DefaultPreprocessor', 'batch_size': 2, 'patch_size': [16, 320, 320], 'median_image_size_in_voxels': [30.0, 512.0, 512.0], 'spacing': [5.0, 0.48828125, 0.48828125], 'normalization_schemes': ['CTNormalization', 'ZScoreNormalization'], 'use_mask_for_norm': [False, False], 'resampling_fn_data': 'resample_data_or_seg_to_shape', 'resampling_fn_seg': 'resample_data_or_seg_to_shape', 'resampling_fn_data_kwargs': {'is_seg': False, 'order': 3, 'order_z': 0, 'force_separate_z': None}, 'resampling_fn_seg_kwargs': {'is_seg': True, 'order': 1, 'order_z': 0, 'force_separate_z': None}, 'resampling_fn_probabilities': 'resample_data_or_seg_to_shape', 'resampling_fn_probabilities_kwargs': {'is_seg': False, 'order': 1, 'order_z': 0, 'force_separate_z': None}, 'architecture': {'network_class_name': 'dynamic_network_architectures.architectures.unet.PlainConvUNet', 'arch_kwargs': {'n_stages': 7, 'features_per_stage': [32, 64, 128, 256, 320, 320, 320], 'conv_op': 'torch.nn.modules.conv.Conv3d', 'kernel_sizes': [[1, 3, 3], [1, 3, 3], [1, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3]], 'strides': [[1, 1, 1], [1, 2, 2], [1, 2, 2], [1, 2, 2], [2, 2, 2], [2, 2, 2], [1, 2, 2]], 'n_conv_per_stage': [2, 2, 2, 2, 2, 2, 2], 'n_conv_per_stage_decoder': [2, 2, 2, 2, 2, 2], 'conv_bias': True, 'norm_op': 'torch.nn.modules.instancenorm.InstanceNorm3d', 'norm_op_kwargs': {'eps': 1e-05, 'affine': True}, 'dropout_op': None, 'dropout_op_kwargs': None, 'nonlin': 'torch.nn.LeakyReLU', 'nonlin_kwargs': {'inplace': True}}, '_kw_requires_import': ['conv_op', 'norm_op', 'dropout_op', 'nonlin']}, 'batch_dice': False}

These are the global plan.json settings:
 {'dataset_name': 'Dataset114_PHESICH_PHE_ICHTeacherPrior', 'plans_name': 'nnUNetPlans', 'original_median_spacing_after_transp': [5.0, 0.48828125, 0.48828125], 'original_median_shape_after_transp': [30, 512, 512], 'image_reader_writer': 'SimpleITKIO', 'transpose_forward': [0, 1, 2], 'transpose_backward': [0, 1, 2], 'experiment_planner_used': 'ExperimentPlanner', 'label_manager': 'LabelManager', 'foreground_intensity_properties_per_channel': {'0': {'max': 99.0, 'mean': 24.356889724731445, 'median': 24.0, 'min': -2.0, 'percentile_00_5': 12.0, 'percentile_99_5': 63.0, 'std': 6.437611103057861}, '1': {'max': 1.0, 'mean': 0.0185715239495039, 'median': 0.0, 'min': 0.0, 'percentile_00_5': 0.0, 'percentile_99_5': 1.0, 'std': 0.13500629365444183}}}

2026-06-17 16:49:46.836095: Unable to plot network architecture:
2026-06-17 16:49:46.836095: No module named 'hiddenlayer'
2026-06-17 16:49:46.854822:
2026-06-17 16:49:46.854822: Epoch 0
2026-06-17 16:49:46.855822: Current learning rate: 0.01
2026-06-17 16:53:32.909401: train_loss -0.0841
2026-06-17 16:53:32.909401: val_loss -0.1905
2026-06-17 16:53:32.909401: Pseudo dice [0.2883]
2026-06-17 16:53:32.910403: Epoch time: 226.06 s
2026-06-17 16:53:32.910403: Yayy! New best EMA pseudo Dice: 0.2883
2026-06-17 16:53:33.797103:
2026-06-17 16:53:33.797103: Epoch 1
2026-06-17 16:53:33.798103: Current learning rate: 0.00996
2026-06-17 16:57:05.631208: train_loss -0.2455
2026-06-17 16:57:05.631208: val_loss -0.2798
2026-06-17 16:57:05.631208: Pseudo dice [0.3565]
2026-06-17 16:57:05.632209: Epoch time: 211.84 s
2026-06-17 16:57:05.632209: Yayy! New best EMA pseudo Dice: 0.2951
2026-06-17 16:57:06.606177:
2026-06-17 16:57:06.607177: Epoch 2
2026-06-17 16:57:06.607177: Current learning rate: 0.00993
2026-06-17 17:00:36.523527: train_loss -0.2896
2026-06-17 17:00:36.524040: val_loss -0.2898
2026-06-17 17:00:36.524040: Pseudo dice [0.3659]
2026-06-17 17:00:36.524549: Epoch time: 209.92 s
2026-06-17 17:00:36.524549: Yayy! New best EMA pseudo Dice: 0.3022
2026-06-17 17:00:37.642850:
2026-06-17 17:00:37.642850: Epoch 3
2026-06-17 17:00:37.643851: Current learning rate: 0.00989
2026-06-17 17:04:09.520692: train_loss -0.2919
2026-06-17 17:04:09.520692: val_loss -0.3108
2026-06-17 17:04:09.521693: Pseudo dice [0.3731]
2026-06-17 17:04:09.521693: Epoch time: 211.88 s
2026-06-17 17:04:09.521693: Yayy! New best EMA pseudo Dice: 0.3093
2026-06-17 17:04:10.477345:
2026-06-17 17:04:10.477345: Epoch 4
2026-06-17 17:04:10.478344: Current learning rate: 0.00986
2026-06-17 17:07:41.757776: train_loss -0.3243
2026-06-17 17:07:41.758775: val_loss -0.3229
2026-06-17 17:07:41.758775: Pseudo dice [0.3739]
2026-06-17 17:07:41.758775: Epoch time: 211.28 s
2026-06-17 17:07:41.758775: Yayy! New best EMA pseudo Dice: 0.3157
2026-06-17 17:07:42.748787:
2026-06-17 17:07:42.749787: Epoch 5
2026-06-17 17:07:42.749787: Current learning rate: 0.00982
2026-06-17 17:11:14.502404: train_loss -0.3435
2026-06-17 17:11:14.502404: val_loss -0.3169
2026-06-17 17:11:14.503404: Pseudo dice [0.3814]
2026-06-17 17:11:14.503404: Epoch time: 211.75 s
2026-06-17 17:11:14.503404: Yayy! New best EMA pseudo Dice: 0.3223
2026-06-17 17:11:15.473294:
2026-06-17 17:11:15.474295: Epoch 6
2026-06-17 17:11:15.474295: Current learning rate: 0.00978
2026-06-17 17:14:48.213939: train_loss -0.3372
2026-06-17 17:14:48.213939: val_loss -0.3669
2026-06-17 17:14:48.214926: Pseudo dice [0.4104]
2026-06-17 17:14:48.214926: Epoch time: 212.74 s
2026-06-17 17:14:48.214926: Yayy! New best EMA pseudo Dice: 0.3311
2026-06-17 17:14:49.175158:
2026-06-17 17:14:49.175158: Epoch 7
2026-06-17 17:14:49.175158: Current learning rate: 0.00975
2026-06-17 17:18:26.286760: train_loss -0.3347
2026-06-17 17:18:26.286760: val_loss -0.3389
2026-06-17 17:18:26.286760: Pseudo dice [0.3847]
2026-06-17 17:18:26.287765: Epoch time: 217.11 s
2026-06-17 17:18:26.287765: Yayy! New best EMA pseudo Dice: 0.3365
2026-06-17 17:18:27.262643:
2026-06-17 17:18:27.263637: Epoch 8
2026-06-17 17:18:27.263637: Current learning rate: 0.00971
2026-06-17 17:22:01.331170: train_loss -0.3538
2026-06-17 17:22:01.332170: val_loss -0.3405
2026-06-17 17:22:01.332170: Pseudo dice [0.3667]
2026-06-17 17:22:01.332170: Epoch time: 214.07 s
2026-06-17 17:22:01.333163: Yayy! New best EMA pseudo Dice: 0.3395
2026-06-17 17:22:02.323451:
2026-06-17 17:22:02.323451: Epoch 9
2026-06-17 17:22:02.323451: Current learning rate: 0.00968
2026-06-17 17:25:36.102828: train_loss -0.3667
2026-06-17 17:25:36.103829: val_loss -0.3415
2026-06-17 17:25:36.103829: Pseudo dice [0.3897]
2026-06-17 17:25:36.103829: Epoch time: 213.78 s
2026-06-17 17:25:36.104845: Yayy! New best EMA pseudo Dice: 0.3445
2026-06-17 17:25:37.060898:
2026-06-17 17:25:37.060898: Epoch 10
2026-06-17 17:25:37.061898: Current learning rate: 0.00964
2026-06-17 17:29:10.540692: train_loss -0.3651
2026-06-17 17:29:10.540692: val_loss -0.3745
2026-06-17 17:29:10.540692: Pseudo dice [0.4074]
2026-06-17 17:29:10.541692: Epoch time: 213.48 s
2026-06-17 17:29:10.541692: Yayy! New best EMA pseudo Dice: 0.3508
2026-06-17 17:29:11.506759:
2026-06-17 17:29:11.506759: Epoch 11
2026-06-17 17:29:11.506759: Current learning rate: 0.0096
2026-06-17 17:32:40.694168: train_loss -0.3939
2026-06-17 17:32:40.694168: val_loss -0.3685
2026-06-17 17:32:40.695169: Pseudo dice [0.4152]
2026-06-17 17:32:40.695169: Epoch time: 209.19 s
2026-06-17 17:32:40.695169: Yayy! New best EMA pseudo Dice: 0.3572
2026-06-17 17:32:41.671293:
2026-06-17 17:32:41.672299: Epoch 12
2026-06-17 17:32:41.672299: Current learning rate: 0.00957
2026-06-17 17:36:15.432527: train_loss -0.3706
2026-06-17 17:36:15.432527: val_loss -0.3521
2026-06-17 17:36:15.432527: Pseudo dice [0.3692]
2026-06-17 17:36:15.433544: Epoch time: 213.76 s
2026-06-17 17:36:15.433544: Yayy! New best EMA pseudo Dice: 0.3584
2026-06-17 17:36:16.404421:
2026-06-17 17:36:16.404421: Epoch 13
2026-06-17 17:36:16.404421: Current learning rate: 0.00953
2026-06-17 17:39:46.128057: train_loss -0.3743
2026-06-17 17:39:46.128057: val_loss -0.3818
2026-06-17 17:39:46.129058: Pseudo dice [0.4153]
2026-06-17 17:39:46.129058: Epoch time: 209.72 s
2026-06-17 17:39:46.129058: Yayy! New best EMA pseudo Dice: 0.3641
2026-06-17 17:39:47.104239:
2026-06-17 17:39:47.104239: Epoch 14
2026-06-17 17:39:47.104239: Current learning rate: 0.00949
2026-06-17 17:43:13.263248: train_loss -0.3871
2026-06-17 17:43:13.263248: val_loss -0.346
2026-06-17 17:43:13.264442: Pseudo dice [0.4017]
2026-06-17 17:43:13.264442: Epoch time: 206.16 s
2026-06-17 17:43:13.264442: Yayy! New best EMA pseudo Dice: 0.3679
2026-06-17 17:43:13.841381:
2026-06-17 17:43:13.841381: Epoch 15
2026-06-17 17:43:13.842381: Current learning rate: 0.00946
2026-06-17 17:46:38.452448: train_loss -0.382
2026-06-17 17:46:38.452448: val_loss -0.4058
2026-06-17 17:46:38.452448: Pseudo dice [0.4374]
2026-06-17 17:46:38.453448: Epoch time: 204.61 s
2026-06-17 17:46:38.453448: Yayy! New best EMA pseudo Dice: 0.3748
2026-06-17 17:46:39.437486:
2026-06-17 17:46:39.437486: Epoch 16
2026-06-17 17:46:39.438497: Current learning rate: 0.00942
2026-06-17 17:50:15.468868: train_loss -0.3893
2026-06-17 17:50:15.468868: val_loss -0.3901
2026-06-17 17:50:15.468868: Pseudo dice [0.4198]
2026-06-17 17:50:15.469870: Epoch time: 216.03 s
2026-06-17 17:50:15.469870: Yayy! New best EMA pseudo Dice: 0.3793
2026-06-17 17:50:16.471385:
2026-06-17 17:50:16.472385: Epoch 17
2026-06-17 17:50:16.472385: Current learning rate: 0.00939
2026-06-17 17:53:51.296607: train_loss -0.3962
2026-06-17 17:53:51.296607: val_loss -0.351
2026-06-17 17:53:51.297614: Pseudo dice [0.3942]
2026-06-17 17:53:51.297614: Epoch time: 214.83 s
2026-06-17 17:53:51.297614: Yayy! New best EMA pseudo Dice: 0.3808
2026-06-17 17:53:52.046182:
2026-06-17 17:53:52.046182: Epoch 18
2026-06-17 17:53:52.046182: Current learning rate: 0.00935
2026-06-17 17:57:27.163554: train_loss -0.3872
2026-06-17 17:57:27.164553: val_loss -0.3845
2026-06-17 17:57:27.164553: Pseudo dice [0.4286]
2026-06-17 17:57:27.164553: Epoch time: 215.12 s
2026-06-17 17:57:27.164553: Yayy! New best EMA pseudo Dice: 0.3856
2026-06-17 17:57:28.159822:
2026-06-17 17:57:28.159822: Epoch 19
2026-06-17 17:57:28.159822: Current learning rate: 0.00931
2026-06-17 18:01:03.914181: train_loss -0.3987
2026-06-17 18:01:03.914181: val_loss -0.4187
2026-06-17 18:01:03.915184: Pseudo dice [0.4405]
2026-06-17 18:01:03.915184: Epoch time: 215.76 s
2026-06-17 18:01:03.915184: Yayy! New best EMA pseudo Dice: 0.3911
2026-06-17 18:01:04.931017:
2026-06-17 18:01:04.932009: Epoch 20
2026-06-17 18:01:04.932009: Current learning rate: 0.00928
2026-06-17 18:04:43.886284: train_loss -0.3959
2026-06-17 18:04:43.887284: val_loss -0.4208
2026-06-17 18:04:43.887284: Pseudo dice [0.4518]
2026-06-17 18:04:43.887284: Epoch time: 218.96 s
2026-06-17 18:04:43.888285: Yayy! New best EMA pseudo Dice: 0.3971
2026-06-17 18:04:44.899644:
2026-06-17 18:04:44.899644: Epoch 21
2026-06-17 18:04:44.899644: Current learning rate: 0.00924
2026-06-17 18:08:27.316665: train_loss -0.3902
2026-06-17 18:08:27.317503: val_loss -0.3516
2026-06-17 18:08:27.317503: Pseudo dice [0.3778]
2026-06-17 18:08:27.317503: Epoch time: 222.42 s
2026-06-17 18:08:27.933048:
2026-06-17 18:08:27.934047: Epoch 22
2026-06-17 18:08:27.934047: Current learning rate: 0.0092
2026-06-17 18:12:11.675525: train_loss -0.3924
2026-06-17 18:12:11.675525: val_loss -0.3758
2026-06-17 18:12:11.676516: Pseudo dice [0.4045]
2026-06-17 18:12:11.676516: Epoch time: 223.74 s
2026-06-17 18:12:12.299237:
2026-06-17 18:12:12.300237: Epoch 23
2026-06-17 18:12:12.300237: Current learning rate: 0.00917
2026-06-17 18:15:53.218469: train_loss -0.4001
2026-06-17 18:15:53.219471: val_loss -0.4214
2026-06-17 18:15:53.219471: Pseudo dice [0.4575]
2026-06-17 18:15:53.219471: Epoch time: 220.92 s
2026-06-17 18:15:53.220470: Yayy! New best EMA pseudo Dice: 0.4023
2026-06-17 18:15:54.194259:
2026-06-17 18:15:54.194259: Epoch 24
2026-06-17 18:15:54.195258: Current learning rate: 0.00913
2026-06-17 18:19:36.217508: train_loss -0.3888
2026-06-17 18:19:36.218514: val_loss -0.4318
2026-06-17 18:19:36.218514: Pseudo dice [0.4709]
2026-06-17 18:19:36.218514: Epoch time: 222.02 s
2026-06-17 18:19:36.219509: Yayy! New best EMA pseudo Dice: 0.4091
2026-06-17 18:19:37.206369:
2026-06-17 18:19:37.206369: Epoch 25
2026-06-17 18:19:37.207367: Current learning rate: 0.0091
2026-06-17 18:22:52.619825: train_loss -0.4077
2026-06-17 18:22:52.619825: val_loss -0.3897
2026-06-17 18:22:52.619825: Pseudo dice [0.4223]
2026-06-17 18:22:52.619825: Epoch time: 195.41 s
2026-06-17 18:22:52.620817: Yayy! New best EMA pseudo Dice: 0.4105
2026-06-17 18:22:53.235162:
2026-06-17 18:22:53.235162: Epoch 26
2026-06-17 18:22:53.235162: Current learning rate: 0.00906
2026-06-17 18:25:49.763302: train_loss -0.4293
2026-06-17 18:25:49.763302: val_loss -0.4087
2026-06-17 18:25:49.764304: Pseudo dice [0.4408]
2026-06-17 18:25:49.764304: Epoch time: 176.53 s
2026-06-17 18:25:49.764304: Yayy! New best EMA pseudo Dice: 0.4135
2026-06-17 18:25:50.663583:
2026-06-17 18:25:50.663583: Epoch 27
2026-06-17 18:25:50.663583: Current learning rate: 0.00902
2026-06-17 18:28:49.731765: train_loss -0.4213
2026-06-17 18:28:49.732765: val_loss -0.3824
2026-06-17 18:28:49.732765: Pseudo dice [0.409]
2026-06-17 18:28:49.732765: Epoch time: 179.07 s
2026-06-17 18:28:50.063202:
2026-06-17 18:28:50.064203: Epoch 28
2026-06-17 18:28:50.064203: Current learning rate: 0.00899
2026-06-17 18:31:48.500852: train_loss -0.4188
2026-06-17 18:31:48.501853: val_loss -0.4054
2026-06-17 18:31:48.501853: Pseudo dice [0.4214]
2026-06-17 18:31:48.501853: Epoch time: 178.44 s
2026-06-17 18:31:48.501853: Yayy! New best EMA pseudo Dice: 0.4139
2026-06-17 18:31:49.077632:
2026-06-17 18:31:49.077632: Epoch 29
2026-06-17 18:31:49.077632: Current learning rate: 0.00895
2026-06-17 18:35:23.504329: train_loss -0.421
2026-06-17 18:35:23.504329: val_loss -0.3433
2026-06-17 18:35:23.504329: Pseudo dice [0.3761]
2026-06-17 18:35:23.505329: Epoch time: 214.43 s
2026-06-17 18:35:24.140810:
2026-06-17 18:35:24.141791: Epoch 30
2026-06-17 18:35:24.141791: Current learning rate: 0.00891
2026-06-17 18:39:02.551462: train_loss -0.4089
2026-06-17 18:39:02.552461: val_loss -0.3868
2026-06-17 18:39:02.552461: Pseudo dice [0.4239]
2026-06-17 18:39:02.552461: Epoch time: 218.41 s
2026-06-17 18:39:03.194376:
2026-06-17 18:39:03.195367: Epoch 31
2026-06-17 18:39:03.195367: Current learning rate: 0.00888
2026-06-17 18:42:48.511843: train_loss -0.4175
2026-06-17 18:42:48.511843: val_loss -0.408
2026-06-17 18:42:48.512833: Pseudo dice [0.4464]
2026-06-17 18:42:48.512833: Epoch time: 225.32 s
2026-06-17 18:42:48.512833: Yayy! New best EMA pseudo Dice: 0.415
2026-06-17 18:42:49.522225:
2026-06-17 18:42:49.522225: Epoch 32
2026-06-17 18:42:49.523224: Current learning rate: 0.00884
2026-06-17 18:46:26.206819: train_loss -0.4222
2026-06-17 18:46:26.206819: val_loss -0.411
2026-06-17 18:46:26.206819: Pseudo dice [0.4506]
2026-06-17 18:46:26.207838: Epoch time: 216.69 s
2026-06-17 18:46:26.207838: Yayy! New best EMA pseudo Dice: 0.4185
2026-06-17 18:46:27.210416:
2026-06-17 18:46:27.210416: Epoch 33
2026-06-17 18:46:27.211414: Current learning rate: 0.0088
2026-06-17 18:50:10.571228: train_loss -0.4339
2026-06-17 18:50:10.572228: val_loss -0.4303
2026-06-17 18:50:10.572228: Pseudo dice [0.4515]
2026-06-17 18:50:10.572228: Epoch time: 223.36 s
2026-06-17 18:50:10.572228: Yayy! New best EMA pseudo Dice: 0.4218
2026-06-17 18:50:11.585117:
2026-06-17 18:50:11.585117: Epoch 34
2026-06-17 18:50:11.586118: Current learning rate: 0.00877
2026-06-17 18:53:36.720130: train_loss -0.4298
2026-06-17 18:53:36.720130: val_loss -0.3892
2026-06-17 18:53:36.720130: Pseudo dice [0.4302]
2026-06-17 18:53:36.720130: Epoch time: 205.14 s
2026-06-17 18:53:36.721130: Yayy! New best EMA pseudo Dice: 0.4227
2026-06-17 18:53:37.325880:
2026-06-17 18:53:37.325880: Epoch 35
2026-06-17 18:53:37.325880: Current learning rate: 0.00873
2026-06-17 18:56:37.829376: train_loss -0.4185
2026-06-17 18:56:37.830374: val_loss -0.4085
2026-06-17 18:56:37.830374: Pseudo dice [0.422]
2026-06-17 18:56:37.830374: Epoch time: 180.5 s
2026-06-17 18:56:38.169529:
2026-06-17 18:56:38.169529: Epoch 36
2026-06-17 18:56:38.169529: Current learning rate: 0.00869
2026-06-17 18:59:37.617410: train_loss -0.415
2026-06-17 18:59:37.617410: val_loss -0.3967
2026-06-17 18:59:37.617410: Pseudo dice [0.4166]
2026-06-17 18:59:37.617410: Epoch time: 179.45 s
2026-06-17 18:59:37.957196:
2026-06-17 18:59:37.957196: Epoch 37
2026-06-17 18:59:37.957196: Current learning rate: 0.00866
2026-06-17 19:02:36.752257: train_loss -0.4138
2026-06-17 19:02:36.753264: val_loss -0.4134
2026-06-17 19:02:36.753264: Pseudo dice [0.4451]
2026-06-17 19:02:36.753264: Epoch time: 178.8 s
2026-06-17 19:02:36.753264: Yayy! New best EMA pseudo Dice: 0.4243
2026-06-17 19:02:37.368378:
2026-06-17 19:02:37.368378: Epoch 38
2026-06-17 19:02:37.369371: Current learning rate: 0.00862
2026-06-17 19:05:36.465088: train_loss -0.4215
2026-06-17 19:05:36.465088: val_loss -0.4005
2026-06-17 19:05:36.466076: Pseudo dice [0.4353]
2026-06-17 19:05:36.466076: Epoch time: 179.1 s
2026-06-17 19:05:36.466076: Yayy! New best EMA pseudo Dice: 0.4254
2026-06-17 19:05:37.072179:
2026-06-17 19:05:37.072179: Epoch 39
2026-06-17 19:05:37.072179: Current learning rate: 0.00858
2026-06-17 19:08:35.628756: train_loss -0.4428
2026-06-17 19:08:35.629748: val_loss -0.4135
2026-06-17 19:08:35.629748: Pseudo dice [0.451]
2026-06-17 19:08:35.629748: Epoch time: 178.56 s
2026-06-17 19:08:35.629748: Yayy! New best EMA pseudo Dice: 0.428
2026-06-17 19:08:36.244309:
2026-06-17 19:08:36.244309: Epoch 40
2026-06-17 19:08:36.245309: Current learning rate: 0.00855
2026-06-17 19:11:35.147666: train_loss -0.4255
2026-06-17 19:11:35.147666: val_loss -0.3874
2026-06-17 19:11:35.148667: Pseudo dice [0.4093]
2026-06-17 19:11:35.148667: Epoch time: 178.9 s
2026-06-17 19:11:35.499652:
2026-06-17 19:11:35.499652: Epoch 41
2026-06-17 19:11:35.499652: Current learning rate: 0.00851
2026-06-17 19:14:35.118109: train_loss -0.4566
2026-06-17 19:14:35.118109: val_loss -0.4004
2026-06-17 19:14:35.119103: Pseudo dice [0.4317]
2026-06-17 19:14:35.119103: Epoch time: 179.62 s
2026-06-17 19:14:35.484413:
2026-06-17 19:14:35.485413: Epoch 42
2026-06-17 19:14:35.485413: Current learning rate: 0.00847
2026-06-17 19:17:35.647445: train_loss -0.4468
2026-06-17 19:17:35.648451: val_loss -0.4336
2026-06-17 19:17:35.648451: Pseudo dice [0.4707]
2026-06-17 19:17:35.648451: Epoch time: 180.16 s
2026-06-17 19:17:35.648451: Yayy! New best EMA pseudo Dice: 0.4311
2026-06-17 19:17:36.247178:
2026-06-17 19:17:36.247178: Epoch 43
2026-06-17 19:17:36.247178: Current learning rate: 0.00844
2026-06-17 19:20:34.843339: train_loss -0.416

## 9. Predict test set and evaluate PHE

In [11]:
RUN_PHE_PREDICT = True
RUN_PHE_EVALUATE = True
DISABLE_TTA = False
CHECKPOINT = 'auto'

imagesTs = DATASET_DIR / 'imagesTs'
labelsTs = DATASET_DIR / 'labelsTs'
MODEL_DIR = NNUNET_RESULTS / DATASET_NAME / f'{TRAINER}__{PLANS}__{CONFIGURATION}'
FOLD_DIR = MODEL_DIR / f'fold_{FOLD}'

def resolve_checkpoint_name(checkpoint_setting='auto'):
    if checkpoint_setting != 'auto':
        ckpt = FOLD_DIR / checkpoint_setting
        if not ckpt.exists():
            available = sorted(p.name for p in FOLD_DIR.glob('checkpoint*.pth')) if FOLD_DIR.exists() else []
            raise FileNotFoundError(f'Missing checkpoint: {ckpt}. Available: {available}')
        return checkpoint_setting
    for name in ['checkpoint_best.pth', 'checkpoint_final.pth', 'checkpoint_latest.pth']:
        if (FOLD_DIR / name).exists():
            return name
    available = sorted(p.name for p in FOLD_DIR.glob('checkpoint*.pth')) if FOLD_DIR.exists() else []
    raise FileNotFoundError(f'No checkpoint found in {FOLD_DIR}. Available: {available}')

RESOLVED_CHECKPOINT = resolve_checkpoint_name(CHECKPOINT)
PRED_DIR = OUTPUT_ROOT / f'predictions_{CONFIGURATION}_{TRAINER}_fold{FOLD}_{RESOLVED_CHECKPOINT.replace(".pth", "")}'
SUMMARY_JSON = PRED_DIR / 'summary.json'

print('Model dir        :', MODEL_DIR)
print('Fold dir         :', FOLD_DIR)
print('Using checkpoint :', RESOLVED_CHECKPOINT)

if RUN_PHE_PREDICT:
    import torch
    from nnunetv2.inference.predict_from_raw_data import nnUNetPredictor
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    print('PHE predict device:', device)
    predictor = nnUNetPredictor(
        tile_step_size=0.5,
        use_gaussian=True,
        use_mirroring=not DISABLE_TTA,
        perform_everything_on_device=(device.type == 'cuda'),
        device=device,
        verbose=False,
        verbose_preprocessing=False,
        allow_tqdm=True,
    )
    predictor.initialize_from_trained_model_folder(
        str(MODEL_DIR),
        use_folds=(FOLD,),
        checkpoint_name=RESOLVED_CHECKPOINT,
    )
    predictor.predict_from_files(
        str(imagesTs),
        str(PRED_DIR),
        save_probabilities=False,
        overwrite=True,
        num_processes_preprocessing=1,
        num_processes_segmentation_export=1,
        folder_with_segs_from_prev_stage=None,
        num_parts=1,
        part_id=0,
    )
else:
    print('Skipped prediction. Set RUN_PHE_PREDICT=True to run inference.')

if RUN_PHE_EVALUATE:
    from nnunetv2.evaluation.evaluate_predictions import evaluate_folder_entry_point
    plans_file = NNUNET_PREPROCESSED / DATASET_NAME / f'{PLANS}.json'
    dataset_json_file = DATASET_DIR / 'dataset.json'
    call_entrypoint(evaluate_folder_entry_point, [
        'nnUNetv2_evaluate_folder',
        str(labelsTs),
        str(PRED_DIR),
        '-djfile', str(dataset_json_file),
        '-pfile', str(plans_file),
        '-o', str(SUMMARY_JSON),
        '-np', '2',
    ])
else:
    print('Skipped evaluation. Set RUN_PHE_EVALUATE=True after prediction.')

print('Prediction dir:', PRED_DIR)
print('Summary json  :', SUMMARY_JSON)

Model dir        : D:\Thuy_Loi\Nam_3\CT_xuathuyetnao\outputs_02_14_nnunet_phe_ich_teacher_prior\nnunet_workdir\nnUNet_results\Dataset114_PHESICH_PHE_ICHTeacherPrior\nnUNetTrainer_250epochs__nnUNetPlans__3d_fullres
Fold dir         : D:\Thuy_Loi\Nam_3\CT_xuathuyetnao\outputs_02_14_nnunet_phe_ich_teacher_prior\nnunet_workdir\nnUNet_results\Dataset114_PHESICH_PHE_ICHTeacherPrior\nnUNetTrainer_250epochs__nnUNetPlans__3d_fullres\fold_0
Using checkpoint : checkpoint_best.pth
PHE predict device: cuda
There are 11 cases in the source folder
I am process 0 out of 1 (max process ID is 0, we start counting with 0!)
There are 11 cases that I would like to predict

Predicting phe_0002:
perform_everything_on_device: True

100%|██████████| 27/27 [00:13<00:00,  1.95it/s]

sending off prediction to background worker for resampling and export
done with phe_0002

Predicting phe_0029:
perform_everything_on_device: True

100%|██████████| 12/12 [00:05<00:00,  2.14it/s]

sending off prediction to background worker for resampling and export
done with phe_0029

Predicting phe_0033:
perform_everything_on_device: True

100%|██████████| 27/27 [00:13<00:00,  1.98it/s]

sending off prediction to background worker for resampling and export
done with phe_0033

Predicting phe_0051:
perform_everything_on_device: True

100%|██████████| 27/27 [00:13<00:00,  1.99it/s]

sending off prediction to background worker for resampling and export
done with phe_0051

Predicting phe_0061:
perform_everything_on_device: True

100%|██████████| 27/27 [00:13<00:00,  1.99it/s]

sending off prediction to background worker for resampling and export
done with phe_0061

Predicting phe_0084:
perform_everything_on_device: True

100%|██████████| 12/12 [00:05<00:00,  2.13it/s]

sending off prediction to background worker for resampling and export
done with phe_0084

Predicting phe_0095:
perform_everything_on_device: True

100%|██████████| 27/27 [00:13<00:00,  1.98it/s]

sending off prediction to background worker for resampling and export
done with phe_0095

Predicting phe_0096:
perform_everything_on_device: True

100%|██████████| 27/27 [00:13<00:00,  1.99it/s]

sending off prediction to background worker for resampling and export
done with phe_0096

Predicting phe_0113:
perform_everything_on_device: True

100%|██████████| 27/27 [00:13<00:00,  1.98it/s]

sending off prediction to background worker for resampling and export
done with phe_0113

Predicting phe_0116:
perform_everything_on_device: True

100%|██████████| 27/27 [00:13<00:00,  1.99it/s]

sending off prediction to background worker for resampling and export
done with phe_0116

Predicting phe_0167:
perform_everything_on_device: True

100%|██████████| 12/12 [00:05<00:00,  2.13it/s]

sending off prediction to background worker for resampling and export
done with phe_0167
GPU prediction completed. Waiting for remaining segmentation exports to finish...

Collecting results: 100%|██████████| 11/11 [00:00<00:00, 27.95it/s]

Segmentation export complete.
>>> nnUNetv2_evaluate_folder D:\Thuy_Loi\Nam_3\CT_xuathuyetnao\outputs_02_14_nnunet_phe_ich_teacher_prior\nnunet_workdir\nnUNet_raw\Dataset114_PHESICH_PHE_ICHTeacherPrior\labelsTs D:\Thuy_Loi\Nam_3\CT_xuathuyetnao\outputs_02_14_nnunet_phe_ich_teacher_prior\predictions_3d_fullres_nnUNetTrainer_250epochs_fold0_checkpoint_best -djfile D:\Thuy_Loi\Nam_3\CT_xuathuyetnao\outputs_02_14_nnunet_phe_ich_teacher_prior\nnunet_workdir\nnUNet_raw\Dataset114_PHESICH_PHE_ICHTeacherPrior\dataset.json -pfile D:\Thuy_Loi\Nam_3\CT_xuathuyetnao\outputs_02_14_nnunet_phe_ich_teacher_prior\nnunet_workdir\nnUNet_preprocessed\Dataset114_PHESICH_PHE_ICHTeacherPrior\nnUNetPlans.json -o D:\Thuy_Loi\Nam_3\CT_xuathuyetnao\outputs_02_14_nnunet_phe_ich_teacher_prior\predictions_3d_fullres_nnUNetTrainer_250epochs_fold0_checkpoint_best\summary.json -np 2
Using <class 'nnunetv2.imageio.simpleitk_reader_writer.SimpleITKIO'> reader/writer
Done in 0.0 min
Prediction dir: D:\Thuy_Loi\Nam_3\CT_xuathuyetnao\outputs_02_14_nnunet_phe_ich_teacher_prior\predictions_3d_fullres_nnUNetTrainer_250epochs_fold0_checkpoint_best
Summary json  : D:\Thuy_Loi\Nam_3\CT_xuathuyetnao\outputs_02_14_nnunet_phe_ich_teacher_prior\predictions_3d_fullres_nnUNetTrainer_250epochs_fold0_checkpoint_best\summary.json

## 10. Export compact metrics CSV

In [12]:
def strip_nii_gz_name(path_like):
    name = Path(str(path_like)).name
    return name[:-7] if name.endswith('.nii.gz') else Path(name).stem

if SUMMARY_JSON.exists():
    with open(SUMMARY_JSON, 'r', encoding='utf-8') as f:
        summary = json.load(f)

    rows = []
    for item in summary.get('metric_per_case', []):
        metrics = item.get('metrics', {}).get('1', {})
        rows.append({
            'case_id': strip_nii_gz_name(item.get('prediction_file', '')),
            'prediction_file': item.get('prediction_file', ''),
            'reference_file': item.get('reference_file', ''),
            **metrics,
        })
    metrics_df = pd.DataFrame(rows)
    metrics_csv = OUTPUT_ROOT / '02_14_phe_ich_prior_metrics_per_case.csv'
    metrics_df.to_csv(metrics_csv, index=False)

    summary_rows = []
    numeric_cols = [c for c in metrics_df.columns if c not in {'case_id', 'prediction_file', 'reference_file'}]
    for col in numeric_cols:
        vals = pd.to_numeric(metrics_df[col], errors='coerce').dropna()
        if len(vals) == 0:
            continue
        summary_rows.append({
            'label': 'PHE',
            'metric': col,
            'mean': float(vals.mean()),
            'median': float(vals.median()),
            'std': float(vals.std(ddof=0)),
            'n': int(len(vals)),
        })
    summary_df = pd.DataFrame(summary_rows)
    summary_csv = OUTPUT_ROOT / '02_14_phe_ich_prior_metrics_summary.csv'
    summary_df.to_csv(summary_csv, index=False)

    print('Foreground mean from nnU-Net summary:')
    print(json.dumps(summary.get('foreground_mean', {}), indent=2))
    print('Wrote:', metrics_csv)
    print('Wrote:', summary_csv)
    display(summary_df)
else:
    print('No summary yet:', SUMMARY_JSON)
    print('Run train -> predict -> evaluate first.')

Foreground mean from nnU-Net summary:
{
  "Dice": 0.3998904803048216,
  "FN": 1033.4545454545455,
  "FP": 1876.0,
  "IoU": 0.2749941751070844,
  "TN": 7836160.7272727275,
  "TP": 1418.5454545454545,
  "n_pred": 3294.5454545454545,
  "n_ref": 2452.0
}
Wrote: D:\Thuy_Loi\Nam_3\CT_xuathuyetnao\outputs_02_14_nnunet_phe_ich_teacher_prior\02_14_phe_ich_prior_metrics_per_case.csv
Wrote: D:\Thuy_Loi\Nam_3\CT_xuathuyetnao\outputs_02_14_nnunet_phe_ich_teacher_prior\02_14_phe_ich_prior_metrics_summary.csv

  label  metric          mean        median            std   n
0   PHE    Dice  3.998905e-01  5.021277e-01       0.226828  11
1   PHE      FN  1.033455e+03  8.650000e+02    1042.656604  11
2   PHE      FP  1.876000e+03  1.818000e+03    1064.383817  11
3   PHE     IoU  2.749942e-01  3.352273e-01       0.178041  11
4   PHE      TN  7.836161e+06  8.382624e+06  800994.682914  11
5   PHE      TP  1.418545e+03  9.240000e+02    1356.074908  11
6   PHE  n_pred  3.294545e+03  2.660000e+03    1722.882224  11
7   PHE   n_ref  2.452000e+03  1.635000e+03    2110.821512  11

## Notes

- `02_13` tao ICH teacher va danh gia ICH tren external test.
- `02_14` load ICH teacher do, predict ICH tren PHE-SICH, roi train PHE model voi `CT + ICH_teacher_prior`.
- De so sanh cong bang voi `02_12`, giu cung split va cung test set 11 case.